### PR TITLE
LPS-98933 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98933

### CODE REVIEW

**Comment by kyle-miho** [comment]
hey @ruben-pulido I updated the export-import tests for fragmentEntry/fragmentEntryLinks to cover fragmentConfiguration as well.

If you notice, the current method of using getBytes from fileUtil, it expects the dependency (*.json) to have the same package path, so this will differ from the fragment.service.test path, requiring us to create a duplicate. Is there a method available where we can combine the dependencies to just be available in the fragment-test module? since they will likely be reusable?

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
> hey @ruben-pulido I updated the export-import tests for fragmentEntry/fragmentEntryLinks to cover fragmentConfiguration as well.
> 
> If you notice, the current method of using getBytes from fileUtil, it expects the dependency (*.json) to have the same package path, so this will differ from the fragment.service.test path, requiring us to create a duplicate. Is there a method available where we can combine the dependencies to just be available in the fragment-test module? since they will likely be reusable?

Hi @kyle-miho! 
Good job on adapting the tests so they cover configuration!

When writing test code I don't focus any longer on trying to avoid duplication, but rather on making sure tests are easy to read and understand, and independent of each other. (I learned this from @cgoncas and you can find quite many articles that try to explain why this is preferred, as this one https://dev.to/avanslaars/don-t-dry-your-tests-2ak0)
Therefore I don't mind the duplicated configuration files in this case.

**Comment by ruben-pulido** [comment]
Sent to @brianchandotcom here: https://github.com/brianchandotcom/liferay-portal/pull/76431

**Pull request closed without merging**
