### PR TITLE
LPS-98528 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98528

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Thanks @kyle-miho!
I've added minor SF changes and sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76118

**Pull request closed without merging**
