### PR TITLE
[TS] LPS-103622 Add context path to redirect url

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-103622

Regression caused by [LPS-78738](https://issues.liferay.com/browse/LPS-78738)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/80160.

**Comment by jorgediaz-lr** [comment]
Thank you, @ruben-pulido !!

**Pull request closed without merging**
