### PR TITLE
LPS-96443 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-96443
cc: @jkappler

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @ruben-pulido I have 2 main concerns here:
1) should any of the asserts / declarations have no line seperation
2) should we be simplifying the names like i originally had? Some examples of very hard to read testcases currently are like:
```
public void testAddFragmentEntryWithFragmentEntryKeyNameCssHtmlJsConfigurationPreviewFileEntryIdTypeAndStatus()
``

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
> Hey @ruben-pulido I have 2 main concerns here:
> 
> 1. should any of the asserts / declarations have no line separation
> 2. should we be simplifying the names like i originally had? Some examples of very hard to read testcases currently are like:
> 
> ```
> public void testAddFragmentEntryWithFragmentEntryKeyNameCssHtmlJsConfigurationPreviewFileEntryIdTypeAndStatus()
> ```

Hi @kyle-miho!

1. I've removed the emptied lines that I believe are not needed
2. Personally I find the long names easier to read, since they allow me to skip the step of translating the letters to the parameter names they are referring to.

I've forwarded the PR to @brianchandotcom with some changes: https://github.com/brianchandotcom/liferay-portal/pull/76369

**Pull request closed without merging**
