### PR TITLE
LPS-98322 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98322

### CODE REVIEW

**Comment by kyle-miho** [comment]
@ricardocousolr Instead of actually activating staging, I checked to make sure that the fragmentEntryLink of the imported and staged model both contain a valid fragmentEntry if they were originally assigned a fragmentEntry (which is why i had it be in a new test instead of adding to the validateImportStagedModel).

Since the original problem is that importing a staged model would not keep the correct fragmentEntryId of the original model, this should be enough to cover it. I tested with the fix reverted and with the current fix, and the test works as intended. Let me know if you have any other concerns or thoughts.

**Comment by ricardocousolr** [comment]
Hi @kyle-miho, 

First of all, thanks for taking the initiative to add a test for this issue, it's really appreciated. 

Second, let me make a few comments I've gathered after playing with the test itself. 

I've tested the fix reverted (here I mean reverting LPS-98038 and LPS-98374) and I've seen that the test passes. So I'm not quite clear on how the test is covering for the case of (activating staging + publishing to live + desactivating staging), I may have misunderstood your explanation. 

Also, with those fixes included, when running the test I've checked that the code added in LPS-98038+LPS-98374 is of no use and yields the same result as if the commits were reverted. I think this is because there's only one FragmentEntry in the database, so both FragmentEntryLinks end up getting the same FragmentEntry. 

I think an important point is that activating staging will create copies for both FragmentEntries and FragmentEntryLinks, but publishing to live only exports/imports FragmentEntryLinks. (There's no _Page Fragments_ menu in the section of _Site Builder_ for _Live_; only in _Staging_.) 

I believe we could improve on the test to be more faithful to the reproducing steps in LPS-98038, but I haven't checked if we have enough infrastructure to make this easy. You may have tried and found it unfeasible. 

Also, I think one thing the test could check is if the `fragmentEntryLink` and the `importedFragmentEntryLink` have _different_ FragmentEntryIds, before deactivating staging. 

What do you think?

P.S.: I'll be on PTO for the next 2 weeks, but when I'm back I could also have a look at improving the test. 

/cc @ruben-pulido

**Comment by kyle-miho** [comment]
oh, weird the revert caused it to fail for me, ill take another look at it

**Comment by kyle-miho** [comment]
@ricardocousolr could you double check reverting those two tickets. I tried again, and still got that reverting those tickets causes the test to fail. This is because when you import a fragmentEntry onto a new site, it will override the current fragmentEntry. The fix forces a refetch of the fragmentEntry within the current site scope, so what should normally be an invalid fragmentEntry is now correctly imported.

I can also just add a test that follows the usecase you specified, to make you feel more confident about the test coverage. I just added this test because it covers the root problem of not re-fetching an incorrectly updated fragment entry (although it won't cover any other problems that can break this usecase).

**Pull request closed without merging**
