### PR TITLE
LPS-99174 Remove properties and use the default ones

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by ruben-pulido** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/76635. [See changes here.](https://github.com/ruben-pulido/liferay-portal/compare/e04cdbc43f14~13...e04cdbc43f14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
