### PR TITLE
LPS-120773 Use always site default language

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Pull request closed without merging**
