### PR TITLE
LPS-105472 No need to use a function here anymore

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-105472

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey Ruben, heres a stabilization change for a test that is very flaky on ci 40-50% failure due to a new test created by https://issues.liferay.com/browse/LPS-105132
We have to manually force the current date to change due to the fact that its possible that the date wont change when we are attempting to check the modified date gets automatically updated

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/81884

**Pull request closed without merging**
